<h2>Veja nossa galeria de aprovados de 2019</h2>
<div class="fb-slick">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/001.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/002.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/003.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/004.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/005.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/006.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/007.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/008.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/009.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/010.jpg">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/011.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/012.jpg">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/013.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/014.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/015.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/016.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/017.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/018.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/019.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/020.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/021.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/022.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/023.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/024.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/025.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/026.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/027.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/028.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/029.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/030.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/031.png">
   <img src="<?php bloginfo('template_url'); ?>/img/fb/032.png">
</div>